server.port=8080
gemini.api.key=${GEMINI_API_KEY:AIzaSyDSZkTlHvFB7DKUldl9ArAmaTrYknwLBWk}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
piston.api.url=https://emkc.org/api/v2/piston/execute
spring.mvc.async.request-timeout=120000
spring.webflux.client.response-timeout=30000
